C_SOURCES_GCC += Gcc/Src/console.c
C_SOURCES_GCC += Gcc/Src/syscalls.c

ASM_SOURCES_GCC += Gcc/Src/startup_stm32n657xx.s

C_SOURCES += $(C_SOURCES_GCC)
ASM_SOURCES += $(ASM_SOURCES_GCC)
ASM_SOURCES_S += $(ASM_SOURCES_S_GCC)
